-- MySQL Script generated by MySQL Workbench
-- qua 18 jun 2025 15:47:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto_dependencia_dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_dependencia_dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_dependencia_dw` DEFAULT CHARACTER SET utf8mb4 ;
USE `projeto_dependencia_dw` ;

-- -----------------------------------------------------
-- Table `projeto_dependencia_dw`.`tb_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_dependencia_dw`.`tb_pessoa` (
  `id_pessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo` ENUM('F', 'J') NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto_dependencia_dw`.`tb_entrevista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_dependencia_dw`.`tb_entrevista` (
  `id_entrevista` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `resumo` VARCHAR(250) NOT NULL,
  `id_pessoa_entrevistador` INT(11) NOT NULL,
  `id_pessoa_entrevistada` INT(11) NOT NULL,
  PRIMARY KEY (`id_entrevista`),
  INDEX `id_pessoa_entrevistador` (`id_pessoa_entrevistador` ASC) VISIBLE,
  INDEX `id_pessoa_entrevistada` (`id_pessoa_entrevistada` ASC) VISIBLE,
  CONSTRAINT `tb_entrevista_ibfk_1`
    FOREIGN KEY (`id_pessoa_entrevistador`)
    REFERENCES `projeto_dependencia_dw`.`tb_pessoa` (`id_pessoa`),
  CONSTRAINT `tb_entrevista_ibfk_2`
    FOREIGN KEY (`id_pessoa_entrevistada`)
    REFERENCES `projeto_dependencia_dw`.`tb_pessoa` (`id_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto_dependencia_dw`.`tb_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_dependencia_dw`.`tb_fisica` (
  `id_fisica` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` CHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_pessoa` INT(11) NOT NULL,
  PRIMARY KEY (`id_fisica`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  INDEX `id_pessoa` (`id_pessoa` ASC) VISIBLE,
  CONSTRAINT `tb_fisica_ibfk_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `projeto_dependencia_dw`.`tb_pessoa` (`id_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `projeto_dependencia_dw`.`tb_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_dependencia_dw`.`tb_juridica` (
  `id_juridica` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` CHAR(14) NOT NULL,
  `razao_social` VARCHAR(100) NOT NULL,
  `nome_fantasia` VARCHAR(100) NOT NULL,
  `id_pessoa` INT(11) NOT NULL,
  PRIMARY KEY (`id_juridica`),
  UNIQUE INDEX `cnpj` (`cnpj` ASC) VISIBLE,
  INDEX `id_pessoa` (`id_pessoa` ASC) VISIBLE,
  CONSTRAINT `tb_juridica_ibfk_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `projeto_dependencia_dw`.`tb_pessoa` (`id_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- MySQL Script generated by ChatGPT
-- Data: 18 jun 2025

-- USE `projeto_dependencia_dw`;

-- -- Inserir pessoas na tabela tb_pessoa
-- INSERT INTO tb_pessoa (nome, email, senha, tipo) VALUES
-- ('João Silva', 'joao.silva@example.com', 'senha123', 'F'),
-- ('Maria Souza', 'maria.souza@example.com', 'senha456', 'F'),
-- ('Empresa XYZ Ltda', 'contato@xyz.com', 'senha789', 'J'),
-- ('Carlos Pereira', 'carlos.pereira@example.com', 'senha321', 'F');

-- -- Inserir entrevistas na tabela tb_entrevista
-- INSERT INTO tb_entrevista (titulo, resumo, id_pessoa_entrevistador, id_pessoa_entrevistada) VALUES
-- ('Entrevista sobre projeto X', 'Discussão detalhada do projeto X.', 1, 2),
-- ('Análise de mercado', 'Entrevista com dados atualizados do mercado.', 4, 3);

-- DROP DATABASE projeto_dependencia_dw;